kind: PodChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  name: pod-fail
  namespace: feeder
spec:
  selector:
    namespaces:
      - feeder
  mode: one
  action: pod-failure
  duration: 10s
  gracePeriod: 0
