apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: feeder
spec:
  type: NodePort
  ports:
    - port: 15672
      protocol: TCP
      targetPort: 15672
  selector:
    app.kubernetes.io/name: rabbitmq-cluster
  sessionAffinity: None
  type: LoadBalancer

